language: python
python:
  - "2.7"
  - "pypy"

# Install numpy, then BioPython
# BioPython doesn't always play well with pip install.
install:
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -q numpy; fi"
  - "pip install -q biopython"
  - "pip install ."
script: nosetests

notifications:
  email:
    - cmccoy@fhcrc.org
